package main

import (
	"flag"
	"fmt"
)

func problem1() {
	fmt.Println("///////////////////////////////////////////////////////////////////////////////")
	fmt.Println("// Problem 1:")
	fmt.Println("// If we list all the natural numbers below 10 that are multiples of 3 or 5,")
	fmt.Println("// we get 3, 5, 6 and 9. The sum of these multiples is 23.")
	fmt.Println("//")
	fmt.Println("///////////////////////////////////////////////////////////////////////////////")
	fmt.Println("\nFind the sum of all the multiples of 3 or 5 below 1000.")

	sum := 0

	for i := 0; i < 1000; i++ {
		if i%3 == 0 || i%5 == 0 {
			sum += i
		}
	}

	fmt.Printf("Answer: %d\n", sum)
}

func problem2() {
	fmt.Println("///////////////////////////////////////////////////////////////////////////////")
	fmt.Println("// Problem 2:")
	fmt.Println("// Each new term in the Fibonacci sequence is generated by adding the previous")
	fmt.Println("// two terms. By starting with 1 and 2, the first 10 terms will be:")
	fmt.Println("// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...")
	fmt.Println("// By considering the terms in the Fibonacci sequence whose values do not exceed")
	fmt.Println("// four million, find the sum of the even-valued terms.")
	fmt.Println("//")
	fmt.Println("///////////////////////////////////////////////////////////////////////////////")

	sum := 0
	x, y := 1, 1

	for y < 4000000 {
		z := x + y

		if z < 4000000 && z%2 == 0 {
			sum += z
		}

		x = y
		y = z
	}

	fmt.Printf("Answer: %d\n", sum)
}

func main() {
	fmt.Println("///////////////////////////////////////////////////////////////////////////////")
	fmt.Println("//")
	fmt.Println("// Project Euler in Go")
	fmt.Println("//")
	fmt.Println("///////////////////////////////////////////////////////////////////////////////")

	problemPtr := flag.String("problem", "error", "Specify a problem to execute (default: problem1)")

	flag.Parse()

	problem := *problemPtr

	switch problem {
	case "1":
		problem1()
	case "2":
		problem2()
	default:
		problem1()
	}
}
